"""dacha logs table

Revision ID: 9b9db490ccd5
Revises: d44f01e4c93b
Create Date: 2019-02-22 14:51:55.672468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9db490ccd5'
down_revision = 'd44f01e4c93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_index(op.f('ix_climate_type'), 'climate', ['type'], unique=False)
    op.create_table('log',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_index(op.f('ix_log_log_type'), 'log', ['log_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_log_type'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_climate_type'), table_name='climate')
    op.drop_table('climate')
    # ### end Alembic commands ###
